Metrics/LineLength:
  Max: 120
SpaceInsideHashLiteralBraces:
  Enabled: false
SpaceInsideBrackets:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
